data:
  data_dir: "/path/to/dance/data"
  seq_length: 50
  stride: 20
  train_ratio: 0.8
  val_ratio: 0.05
  batch_size: 64

model:
  hidden_dim: 384
  latent_dim: 256
  n_layers: 2
  dropout: 0.3

training:
  epochs: 1000
  learning_rate: 0.0003
  beta_min: 0.0001
  beta_max: 0.1
  alpha: 0.25
  gamma: 0.01
  clip_grad: 1.0
  patience: 100
  save_dir: "/path/to/save/dir"
